// =========================================================
// Doctory — Shared Data (Governorates, Specialties, Doctors)
// =========================================================

// ===== 1. Egypt Governorates & Areas (من egypt-data.js) =====
const EGYPT_GOVERNORATES = {
  "القاهرة": [
    "مدينة نصر", "المعادي", "حلوان", "مصر الجديدة", "النزهة",
    "وسط البلد", "الزمالك", "شبرا", "روض الفرج", "الساحل",
    "الزيتون", "حدائق القبة", "الوايلي", "المطرية", "عين شمس",
    "المرج", "السلام أول", "السلام ثاني", "التبين", "دار السلام",
    "السيدة زينب", "الخليفة", "المقطم", "البساتين", "المنيل",
    "مصر القديمة", "عابدين", "الأزبكية", "الموسكي", "باب الشعرية",
    "الدرب الأحمر", "الجمالية", "بولاق", "العباسية", "الزاوية الحمراء",
    "أمبابة الكائنة بالقاهرة", "القاهرة الجديدة (التجمع)", "بدر",
    "الشروق", "العبور", "15 مايو", "المقاولون العرب"
  ],
  "الجيزة": [
    "الدقي", "العجوزة", "المهندسين", "الهرم", "فيصل",
    "بولاق الدكرور", "إمبابة", "أوسيم", "كرداسة", "أبو النمرس",
    "الحوامدية", "البدرشين", "الصف", "أطفيح", "العياط",
    "منشأة القناطر", "6 أكتوبر", "الشيخ زايد", "حدائق الأهرام",
    "الواحات البحرية", "الوراق", "الكيت كات", "الزمالك (جيزة)",
    "العمرانية", "الطالبية"
  ],
  "الإسكندرية": [
    "محرم بك", "العطارين", "الجمرك", "كرموز", "اللبان",
    "وسط الإسكندرية", "المنتزه أول", "المنتزه ثاني", "الرمل أول",
    "الرمل ثاني", "سيدي جابر", "باكوس", "سموحة", "زيزينيا",
    "لوران", "كليوباترا", "العصافرة", "ميامي", "المندرة",
    "أبو قير", "برج العرب", "العامرية", "الدخيلة", "المعمورة",
    "العجمي", "هانوفيل", "سيدي بشر", "محطة الرمل", "جليم"
  ],
  "الدقهلية": [
    "المنصورة", "طلخا", "ميت غمر", "السنبلاوين", "أجا",
    "منية النصر", "الكردي", "بني عبيد", "تمي الأمديد", "المنزلة",
    "ميت سلسيل", "شربين", "المطرية", "بلقاس", "جمصة",
    "دكرنس", "نبروه", "محلة دمنة"
  ],
  "الشرقية": [
    "الزقازيق", "العاشر من رمضان", "بلبيس", "منيا القمح", "أبو حماد",
    "أبو كبير", "فاقوس", "الإبراهيمية", "كفر صقر", "ههيا",
    "مشتول السوق", "أولاد صقر", "ديرب نجم", "الحسينية", "صان الحجر القبلية",
    "القرين", "القنايات", "منشأة أبو عمر"
  ],
  "القليوبية": [
    "بنها", "قليوب", "شبرا الخيمة", "القناطر الخيرية", "طوخ",
    "كفر شكر", "الخانكة", "العبور", "شبين القناطر", "خصوص"
  ],
  "كفر الشيخ": [
    "كفر الشيخ", "دسوق", "فوه", "مطوبس", "بلطيم",
    "الحامول", "بيلا", "الرياض", "سيدي سالم", "قلين",
    "البرلس"
  ],
  "الغربية": [
    "طنطا", "المحلة الكبرى", "كفر الزيات", "زفتى", "السنطة",
    "قطور", "بسيون", "سمنود"
  ],
  "المنوفية": [
    "شبين الكوم", "منوف", "أشمون", "الباجور", "قويسنا",
    "بركة السبع", "تلا", "السادات", "الشهداء"
  ],
  "البحيرة": [
    "دمنهور", "كفر الدوار", "رشيد", "إدكو", "أبو المطامير",
    "أبو حمص", "الدلنجات", "إيتاي البارود", "حوش عيسى", "شبراخيت",
    "كوم حمادة", "بدر (البحيرة)", "وادي النطرون", "النوبارية الجديدة",
    "المحمودية", "الرحمانية"
  ],
  "الإسماعيلية": [
    "الإسماعيلية", "فايد", "القنطرة شرق", "القنطرة غرب",
    "التل الكبير", "القصاصين", "أبو صوير"
  ],
  "بورسعيد": [
    "بورسعيد", "بورفؤاد", "الضواحي", "الزهور", "الشرق",
    "المناخ", "حي العرب", "الجنوب"
  ],
  "السويس": [
    "السويس", "الأربعين", "عتاقة", "الجناين", "فيصل (السويس)",
    "الجناين الجديدة"
  ],
  "بني سويف": [
    "بني سويف", "ببا", "سمسطا", "ناصر", "إهناسيا",
    "الفشن", "الواسطى", "بيبا", "سمالوط (بني سويف)"
  ],
  "الفيوم": [
    "الفيوم", "سنورس", "إطسا", "إبشواي", "طامية",
    "يوسف الصديق (الفيوم)"
  ],
  "المنيا": [
    "المنيا", "ملوي", "سمالوط", "بني مزار", "مغاغة",
    "مطاي", "أبو قرقاص", "ديرمواس", "العدوة"
  ],
  "أسيوط": [
    "أسيوط", "ديروط", "منفلوط", "أبنوب", "أبوتيج",
    "ساحل سليم", "الغنايم", "البداري", "صدفا", "القوصية",
    "الفتح"
  ],
  "سوهاج": [
    "سوهاج", "أخميم", "جرجا", "البلينا", "المراغة",
    "دار السلام (سوهاج)", "ساقلتة", "طما", "طهطا", "جهينة",
    "العسيرات"
  ],
  "قنا": [
    "قنا", "قوص", "نقادة", "أبو تشت", "فرشوط",
    "الوقف", "دشنا", "قفط", "نجع حمادي"
  ],
  "الأقصر": [
    "الأقصر", "إسنا", "أرمنت", "الزينية", "الطود",
    "البياضية", "القرنة"
  ],
  "أسوان": [
    "أسوان", "كوم أمبو", "إدفو", "دراو", "نصر النوبة",
    "كلابشة", "أبو سمبل", "الرديسية"
  ],
  "البحر الأحمر": [
    "الغردقة", "رأس غارب", "سفاجا", "القصير", "مرسى علم",
    "الشلاتين", "حلايب"
  ],
  "الوادي الجديد": [
    "الخارجة", "الداخلة", "الفرافرة", "باريس", "بلاط"
  ],
  "مطروح": [
    "مرسى مطروح", "الحمام", "العلمين", "الضبعة", "سيدي براني",
    "السلوم", "النجيلة", "سيوة"
  ],
  "شمال سيناء": [
    "العريش", "الشيخ زويد", "رفح", "بئر العبد", "نخل",
    "الحسنة"
  ],
  "جنوب سيناء": [
    "الطور", "شرم الشيخ", "دهب", "نويبع", "سانت كاترين",
    "أبو رديس", "أبو زنيمة", "طابا"
  ],
  "دمياط": [
    "دمياط", "رأس البر", "فارسكور", "الزرقا", "كفر سعد",
    "ميت أبو غالب", "الروضة", "السرو", "كفر البطيخ", "عزبة البرج"
  ]
};

const EGYPT_GOVERNORATES_LIST = Object.keys(EGYPT_GOVERNORATES);

function getAreaLabel(governorate) {
  const cityGovernorates = ["القاهرة", "الجيزة", "الإسكندرية"];
  return cityGovernorates.includes(governorate) ? "حي" : "مركز";
}

// ===== 2. Medical Specialties (من specialties-data.js) =====
const MEDICAL_SPECIALTIES = [
  { name: "باطنة عامة", icon: "🩺" },
  { name: "قلب وأوعية دموية", icon: "❤️" },
  { name: "جراحة عامة", icon: "🔬" },
  { name: "عظام ومفاصل", icon: "🦴" },
  { name: "نساء وتوليد", icon: "🤰" },
  { name: "أطفال وحديثي الولادة", icon: "👶" },
  { name: "جلدية وتناسلية وتجميل", icon: "🧴" },
  { name: "عيون", icon: "👁️" },
  { name: "أنف وأذن وحنجرة", icon: "👂" },
  { name: "أسنان", icon: "🦷" },
  { name: "مسالك بولية وتناسلية", icon: "🩻" },
  { name: "مخ وأعصاب وجراحة المخ والأعصاب", icon: "🧠" },
  { name: "نفسية وعلاج إدمان", icon: "🧩" },
  { name: "صدر وأمراض الجهاز التنفسي", icon: "🫁" },
  { name: "غدد صماء وسكر", icon: "💉" },
  { name: "كلى وحالات الفشل الكلوي", icon: "🫘" },
  { name: "كبد وجهاز هضمي", icon: "🫀" },
  { name: "روماتيزم ومناعة", icon: "🦵" },
  { name: "أورام وعلاج كيماوي", icon: "🎗️" },
  { name: "تخسيس وتغذية علاجية", icon: "🥗" },
  { name: "جراحة تجميل وحروق", icon: "✨" },
  { name: "جراحة أوعية دموية", icon: "🩸" },
  { name: "أمراض دم", icon: "🔴" },
  { name: "حساسية ومناعة", icon: "🤧" },
  { name: "علاج طبيعي وتأهيل", icon: "🏃" },
  { name: "تخدير ورعاية مركزة", icon: "💤" },
  { name: "أشعة تشخيصية وتداخلية", icon: "📡" },
  { name: "تحاليل وباثولوجيا إكلينيكية", icon: "🧪" },
  { name: "طب أسرة", icon: "👨‍👩‍👧" },
  { name: "طب الطوارئ", icon: "🚑" },
  { name: "جراحة أطفال", icon: "🧒" },
  { name: "جراحة مسالك بولية للأطفال", icon: "🧒" },
  { name: "أمراض الروماتيزم للأطفال", icon: "🧒" },
  { name: "زراعة الشعر", icon: "💇" },
  { name: "علاج طبيعي للأطفال", icon: "🧒" },
  { name: "طب نفسي للأطفال", icon: "🧸" },
  { name: "علاج الخصوبة وحقن مجهري", icon: "👨‍👩‍👧‍👦" },
  { name: "جراحة المسالك البولية والتناسلية للذكور", icon: "🩺" },
  { name: "السمعيات وعلاج النطق", icon: "🗣️" },
  { name: "طب الأسرة والمجتمع", icon: "🏘️" }
];

// ===== 3. Demo Doctors (من search.js بالكامل مع bio) =====
const DEMO_DOCTORS = [
  {
    id: 1,
    name: "د. أحمد محمود السيد",
    gender: "male",
    specialty: "قلب وأوعية دموية",
    specialtyIcon: "❤️",
    degree: "أستاذ دكتور وإستشاري أمراض القلب — كلية طب القاهرة",
    governorate: "القاهرة",
    area: "مدينة نصر",
    clinic: "عيادات النيل الطبية",
    experience: 22,
    price: 500,
    rating: 4.9,
    reviews: 312,
    initials: "أم",
    featured: true,
    verified: true,
    availableToday: true,
    availableTomorrow: false,
    hasOnline: true,
    avatarColor: "#1B3A6B",
    bio: "د. أحمد محمود السيد هو أستاذ دكتور واستشاري أمراض القلب والقسطرة العلاجية. حاصل على زمالة الكلية الملكية للأطباء بلندن، ويتمتع بخبرة واسعة في علاج حالات القلب المعقدة. عضو هيئة التدريس بكلية طب القاهرة، وله العديد من الأبحاث المنشورة في مجال أمراض القلب التداخلية."
  },
  {
    id: 2,
    name: "د. منى إبراهيم حسن",
    gender: "female",
    specialty: "نساء وتوليد",
    specialtyIcon: "🤰",
    degree: "إستشاري نساء وتوليد — مستشفى القصر العيني",
    governorate: "القاهرة",
    area: "الزمالك",
    clinic: "مركز الأمل لصحة المرأة",
    experience: 18,
    price: 350,
    rating: 4.8,
    reviews: 198,
    initials: "من",
    featured: false,
    verified: true,
    availableToday: true,
    availableTomorrow: false,
    hasOnline: false,
    avatarColor: "#0EA5A4",
    bio: "د. منى إبراهيم هي استشاري نساء وتوليد وعقم، حاصلة على الزمالة المصرية، وتعمل بمستشفى القصر العيني. تقدم رعاية متكاملة للمرأة في جميع مراحل العمر، مع اهتمام خاص بمتابعة الحمل والولادة الطبيعية والقيصرية، وعلاج حالات العقم المتقدمة."
  },
  {
    id: 3,
    name: "د. خالد عبد الرحمن",
    gender: "male",
    specialty: "عظام ومفاصل",
    specialtyIcon: "🦴",
    degree: "أستاذ مساعد جراحة العظام — جامعة عين شمس",
    governorate: "الجيزة",
    area: "المهندسين",
    clinic: "مركز الجيزة التخصصي",
    experience: 15,
    price: 400,
    rating: 4.7,
    reviews: 245,
    initials: "خع",
    featured: false,
    verified: true,
    availableToday: false,
    availableTomorrow: true,
    hasOnline: true,
    avatarColor: "#5B21B6",
    bio: "د. خالد عبد الرحمن هو أستاذ مساعد جراحة العظام والمفاصل بجامعة عين شمس. متخصص في جراحات المناظير والاستبدال الكامل للمفاصل، وله خبرة في معالجة إصابات الملاعب والكسور المعقدة."
  },
  {
    id: 4,
    name: "د. سارة محمد علي",
    gender: "female",
    specialty: "أطفال وحديثي الولادة",
    specialtyIcon: "👶",
    degree: "إستشاري طب أطفال — مستشفى أبو الريش",
    governorate: "القاهرة",
    area: "المعادي",
    clinic: "عيادة الطفل السعيد",
    experience: 12,
    price: 250,
    rating: 4.9,
    reviews: 421,
    initials: "سع",
    featured: true,
    verified: true,
    availableToday: true,
    availableTomorrow: false,
    hasOnline: true,
    avatarColor: "#DC2626",
    bio: "د. سارة محمد علي هي استشاري طب الأطفال وحديثي الولادة، حاصلة على بورد الأطفال المصري. تعمل بمستشفى أبو الريش الجامعي، وتتميز بالتعامل الرقيق مع الأطفال وتقديم الرعاية الشاملة من الولادة حتى المراهقة."
  },
  {
    id: 5,
    name: "د. محمد وليد نصر",
    gender: "male",
    specialty: "باطنة عامة",
    specialtyIcon: "🩺",
    degree: "إستشاري طب باطني — عضو الجمعية المصرية للطب الباطني",
    governorate: "الإسكندرية",
    area: "سموحة",
    clinic: "مركز الرعاية الطبية",
    experience: 20,
    price: 300,
    rating: 4.6,
    reviews: 187,
    initials: "مو",
    featured: false,
    verified: true,
    availableToday: false,
    availableTomorrow: true,
    hasOnline: false,
    avatarColor: "#0369A1",
    bio: "د. محمد وليد نصر هو استشاري طب باطني وأمراض السكر والضغط، له خبرة تزيد عن 20 عاماً في تشخيص وعلاج الأمراض الباطنية المزمنة. يعمل في مركز الرعاية الطبية بالإسكندرية."
  },
  {
    id: 6,
    name: "د. ريم حسام الدين",
    gender: "female",
    specialty: "جلدية وتناسلية وتجميل",
    specialtyIcon: "🧴",
    degree: "إستشاري أمراض جلدية وليزر — بورد أمريكي",
    governorate: "القاهرة",
    area: "مصر الجديدة",
    clinic: "عيادة اللمسة الجميلة",
    experience: 10,
    price: 600,
    rating: 4.8,
    reviews: 534,
    initials: "رح",
    featured: false,
    verified: true,
    availableToday: true,
    availableTomorrow: false,
    hasOnline: true,
    avatarColor: "#BE185D",
    bio: "د. ريم حسام الدين هي استشاري الأمراض الجلدية والتناسلية والعلاج بالليزر، حاصلة على بورد أمريكي. تقدم أحدث التقنيات في علاج حب الشباب، الكلف، التصبغات، وإزالة الشعر بالليزر."
  },
  {
    id: 7,
    name: "د. عمر فاروق طه",
    gender: "male",
    specialty: "مخ وأعصاب وجراحة المخ والأعصاب",
    specialtyIcon: "🧠",
    degree: "أستاذ دكتور طب المخ والأعصاب — جامعة القاهرة",
    governorate: "القاهرة",
    area: "وسط البلد",
    clinic: "معهد الأعصاب القومي",
    experience: 28,
    price: 700,
    rating: 4.9,
    reviews: 276,
    initials: "عف",
    featured: true,
    verified: true,
    availableToday: false,
    availableTomorrow: true,
    hasOnline: false,
    avatarColor: "#1B3A6B",
    bio: "د. عمر فاروق طه هو أستاذ دكتور المخ والأعصاب، وعميد معهد الأعصاب القومي سابقاً. خبير في علاج الصرع والتصلب المتعدد والشلل الرعاش، وله مساهمات عالمية في أبحاث الأعصاب."
  },
  {
    id: 8,
    name: "د. نورا يحيى صالح",
    gender: "female",
    specialty: "عيون",
    specialtyIcon: "👁️",
    degree: "إستشاري طب وجراحة العيون — معهد العيون القومي",
    governorate: "الجيزة",
    area: "الدقي",
    clinic: "مركز الرؤية الواضحة",
    experience: 14,
    price: 350,
    rating: 4.7,
    reviews: 319,
    initials: "نص",
    featured: false,
    verified: true,
    availableToday: true,
    availableTomorrow: false,
    hasOnline: true,
    avatarColor: "#0EA5A4",
    bio: "د. نورا يحيى صالح هي استشاري طب العيون وجراحتها، متخصصة في جراحات المياه البيضاء والليزك، وكذلك علاج حالات الشبكية وجفاف العين."
  },
  {
    id: 9,
    name: "د. طارق إسماعيل عوض",
    gender: "male",
    specialty: "جراحة عامة",
    specialtyIcon: "🔬",
    degree: "إستشاري جراحة عامة وجراحة منظار — بورد أوروبي",
    governorate: "الإسكندرية",
    area: "محرم بك",
    clinic: "مستشفى الشاطبي الجامعي",
    experience: 17,
    price: 450,
    rating: 4.5,
    reviews: 143,
    initials: "طع",
    featured: false,
    verified: false,
    availableToday: false,
    availableTomorrow: true,
    hasOnline: false,
    avatarColor: "#047857",
    bio: "د. طارق إسماعيل عوض هو استشاري الجراحة العامة وجراحة المناظير، حاصل على بورد أوروبي في الجراحة. يجري عمليات المرارة والفتق والقولون بالمنظار، مع خبرة في جراحات الأورام."
  },
  {
    id: 10,
    name: "د. ياسمين كمال رزق",
    gender: "female",
    specialty: "نفسية وعلاج إدمان",
    specialtyIcon: "🧩",
    degree: "إستشاري طب نفسي — زمالة كلية الملكية البريطانية",
    governorate: "القاهرة",
    area: "القاهرة الجديدة (التجمع)",
    clinic: "مركز الصحة النفسية والتوافق",
    experience: 11,
    price: 500,
    rating: 4.8,
    reviews: 389,
    initials: "يك",
    featured: false,
    verified: true,
    availableToday: true,
    availableTomorrow: false,
    hasOnline: true,
    avatarColor: "#7C3AED",
    bio: "د. ياسمين كمال رزق هي استشاري الطب النفسي وعلاج الإدمان، حاصلة على زمالة الكلية الملكية للأطباء النفسيين بلندن. تتعامل مع القلق والاكتئاب واضطرابات الشخصية، وتستخدم أحدث بروتوكولات العلاج السلوكي."
  },
  {
    id: 11,
    name: "د. حسام عبد الله رياض",
    gender: "male",
    specialty: "أسنان",
    specialtyIcon: "🦷",
    degree: "إستشاري تركيبات وزراعة أسنان — جامعة الأزهر",
    governorate: "الجيزة",
    area: "6 أكتوبر",
    clinic: "مركز أكتوبر لطب الأسنان",
    experience: 13,
    price: 200,
    rating: 4.6,
    reviews: 212,
    initials: "حر",
    featured: false,
    verified: true,
    availableToday: true,
    availableTomorrow: false,
    hasOnline: false,
    avatarColor: "#1D4ED8",
    bio: "د. حسام عبد الله رياض هو استشاري تركيبات الأسنان الثابتة والمتحركة وزراعة الأسنان، حاصل على ماجستير من جامعة الأزهر. يقدم خدمات زراعة الأسنان الفورية والتركيبات التجميلية."
  },
  {
    id: 12,
    name: "د. نهى عصام زيدان",
    gender: "female",
    specialty: "غدد صماء وسكر",
    specialtyIcon: "💉",
    degree: "إستشاري الغدد الصماء والسمنة — جامعة عين شمس",
    governorate: "القاهرة",
    area: "النزهة",
    clinic: "مركز السكر والغدد",
    experience: 16,
    price: 400,
    rating: 4.7,
    reviews: 267,
    initials: "نز",
    featured: false,
    verified: true,
    availableToday: false,
    availableTomorrow: true,
    hasOnline: true,
    avatarColor: "#C2410C",
    bio: "د. نهى عصام زيدان هي استشاري الغدد الصماء والسكري والسمنة، حاصلة على دكتوراه من جامعة عين شمس. تعالج حالات السكري من النوع الأول والثاني، وأمراض الغدة الدرقية، واضطرابات الهرمونات."
  },
  {
    id: 13,
    name: "د. رامي شوقي منصور",
    gender: "male",
    specialty: "مسالك بولية وتناسلية",
    specialtyIcon: "🩻",
    degree: "إستشاري المسالك البولية — أستاذ مساعد القصر العيني",
    governorate: "الإسكندرية",
    area: "الرمل أول",
    clinic: "عيادات سبورتنج الطبية",
    experience: 19,
    price: 500,
    rating: 4.5,
    reviews: 98,
    initials: "رم",
    featured: false,
    verified: false,
    availableToday: false,
    availableTomorrow: true,
    hasOnline: false,
    avatarColor: "#0F766E",
    bio: "د. رامي شوقي منصور هو استشاري المسالك البولية والتناسلية، أستاذ مساعد بالقصر العيني. متخصص في جراحات حصوات الكلى وتضخم البروستاتا والضعف الجنسي."
  },
  {
    id: 14,
    name: "د. دينا سامح الشريف",
    gender: "female",
    specialty: "تخسيس وتغذية علاجية",
    specialtyIcon: "🥗",
    degree: "إستشاري التغذية العلاجية والسمنة — بورد عربي",
    governorate: "القاهرة",
    area: "مصر الجديدة",
    clinic: "مركز التغذية والصحة",
    experience: 9,
    price: 300,
    rating: 4.9,
    reviews: 611,
    initials: "دش",
    featured: true,
    verified: true,
    availableToday: true,
    availableTomorrow: false,
    hasOnline: true,
    avatarColor: "#15803D",
    bio: "د. دينا سامح الشريف هي استشاري التغذية العلاجية والسمنة، حاصلة على بورد عربي في التغذية. تصمم برامج غذائية مخصصة لفقدان الوزن وعلاج سوء التغذية والأمراض المرتبطة بالنظام الغذائي."
  },
  {
    id: 15,
    name: "د. أيمن حمدي الزيات",
    gender: "male",
    specialty: "صدر وأمراض الجهاز التنفسي",
    specialtyIcon: "🫁",
    degree: "إستشاري أمراض الصدر والتنفس — جامعة المنصورة",
    governorate: "الدقهلية",
    area: "المنصورة",
    clinic: "مستشفى المنصورة الجامعي",
    experience: 21,
    price: 250,
    rating: 4.6,
    reviews: 154,
    initials: "أز",
    featured: false,
    verified: true,
    availableToday: false,
    availableTomorrow: true,
    hasOnline: false,
    avatarColor: "#1E40AF",
    bio: "د. أيمن حمدي الزيات هو استشاري أمراض الصدر والحساسية والجهاز التنفسي، يعمل بمستشفى المنصورة الجامعي. يشخص ويعالج الربو والانسداد الرئوي المزمن والتهابات الرئة."
  },
  {
    id: 16,
    name: "د. غادة رفعت يوسف",
    gender: "female",
    specialty: "روماتيزم ومناعة",
    specialtyIcon: "🦵",
    degree: "إستشاري الروماتيزم والمناعة الذاتية — زمالة أوروبية",
    governorate: "القاهرة",
    area: "الزيتون",
    clinic: "مركز المفاصل والروماتيزم",
    experience: 14,
    price: 450,
    rating: 4.7,
    reviews: 176,
    initials: "غي",
    featured: false,
    verified: true,
    availableToday: true,
    availableTomorrow: false,
    hasOnline: true,
    avatarColor: "#9D174D",
    bio: "د. غادة رفعت يوسف هي استشاري الروماتيزم وأمراض المناعة الذاتية، حاصلة على زمالة أوروبية. تتخصص في علاج التهاب المفاصل الروماتويدي والذئبة الحمراء وتصلب الجلد."
  },
  {
    id: 17,
    name: "د. كريم مصطفى بدر",
    gender: "male",
    specialty: "أنف وأذن وحنجرة",
    specialtyIcon: "👂",
    degree: "إستشاري الأنف والأذن والحنجرة — أستاذ القاهرة",
    governorate: "الجيزة",
    area: "العجوزة",
    clinic: "مركز الحواس الطبي",
    experience: 16,
    price: 350,
    rating: 4.8,
    reviews: 233,
    initials: "كب",
    featured: false,
    verified: true,
    availableToday: false,
    availableTomorrow: true,
    hasOnline: false,
    avatarColor: "#0369A1",
    bio: "د. كريم مصطفى بدر هو استشاري الأنف والأذن والحنجرة، أستاذ مساعد بكلية طب القاهرة. يجري عمليات تنظير الجيوب الأنفية وزراعة القوقعة وجراحات الحبال الصوتية."
  },
  {
    id: 18,
    name: "د. سلمى أحمد فوزي",
    gender: "female",
    specialty: "كبد وجهاز هضمي",
    specialtyIcon: "🫀",
    degree: "إستشاري أمراض الكبد والجهاز الهضمي — بورد أمريكي",
    governorate: "القاهرة",
    area: "شبرا",
    clinic: "مركز الكبد التخصصي",
    experience: 13,
    price: 400,
    rating: 4.6,
    reviews: 128,
    initials: "سف",
    featured: false,
    verified: true,
    availableToday: true,
    availableTomorrow: false,
    hasOnline: false,
    avatarColor: "#B45309",
    bio: "د. سلمى أحمد فوزي هي استشاري أمراض الكبد والجهاز الهضمي، حاصلة على بورد أمريكي. تعالج التهاب الكبد الفيروسي، تليف الكبد، وقرحة المعدة والقولون العصبي."
  },
  {
    id: 19,
    name: "د. هشام نبيل المسيري",
    gender: "male",
    specialty: "أورام وعلاج كيماوي",
    specialtyIcon: "🎗️",
    degree: "أستاذ دكتور علاج الأورام — مستشفى الأورام القومي",
    governorate: "القاهرة",
    area: "المعادي",
    clinic: "مركز الأمل للأورام",
    experience: 26,
    price: 800,
    rating: 4.9,
    reviews: 187,
    initials: "هم",
    featured: true,
    verified: true,
    availableToday: false,
    availableTomorrow: true,
    hasOnline: false,
    avatarColor: "#7C3AED",
    bio: "د. هشام نبيل المسيري هو أستاذ دكتور علاج الأورام والكيماوي، له خبرة في علاج جميع أنواع الأورام الصلبة وسرطانات الدم. يشغل منصب رئيس قسم الأورام بمستشفى الأورام القومي."
  },
  {
    id: 20,
    name: "د. إيمان رضا عمارة",
    gender: "female",
    specialty: "علاج طبيعي وتأهيل",
    specialtyIcon: "🏃",
    degree: "إستشاري العلاج الطبيعي وتأهيل الحركة — جامعة حلوان",
    governorate: "القاهرة",
    area: "حلوان",
    clinic: "مركز النشاط والحركة",
    experience: 10,
    price: 180,
    rating: 4.7,
    reviews: 302,
    initials: "إع",
    featured: false,
    verified: true,
    availableToday: true,
    availableTomorrow: false,
    hasOnline: true,
    avatarColor: "#0F766E",
    bio: "د. إيمان رضا عمارة هي استشاري العلاج الطبيعي والتأهيل الحركي، متخصصة في إعادة التأهيل بعد العمليات الجراحية والإصابات الرياضية، وتقديم برامج علاجية للشلل والجلطات الدماغية."
  }
];
// ===== Expose legacy globals on window =====
// const/let declared at top level do NOT become window properties
// (unlike var). admin/js/defaults.js and js/data-loader.js read these
// via window.EGYPT_GOVERNORATES / window.MEDICAL_SPECIALTIES /
// window.DEMO_DOCTORS, so without this they are always undefined and
// getDefaults() throws "legacy data.js not loaded".
window.EGYPT_GOVERNORATES = EGYPT_GOVERNORATES;
window.EGYPT_GOVERNORATES_LIST = EGYPT_GOVERNORATES_LIST;
window.MEDICAL_SPECIALTIES = MEDICAL_SPECIALTIES;
window.DEMO_DOCTORS = DEMO_DOCTORS;
